Create database	DBDelivery

Create table Produto(
		CODIGOPRODUTO INT NOT NULL,
		DESCRICAOPRODUTO VARCHAR(100) DEFAULT 'MeuProduto',
		PRECOPRODUTO REAL NOT NULL CHECK(PRECOPRODUTO>=0),
		PRIMARY KEY (CODIGOPRODUTO)
)