//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDSAlmoxarifado.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Area
    {
        public Area()
        {
            this.Colaborador = new HashSet<Colaborador>();
            this.Colaborador1 = new HashSet<Colaborador>();
            this.Colaborador2 = new HashSet<Colaborador>();
        }
    
        public int AREID { get; set; }
        public string AREDESCRICAO { get; set; }
    
        public virtual ICollection<Colaborador> Colaborador { get; set; }
        public virtual ICollection<Colaborador> Colaborador1 { get; set; }
        public virtual ICollection<Colaborador> Colaborador2 { get; set; }
    }
}
