//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDSAlmoxarifado.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bdTDS_AlmoxarifadoEntities1 : DbContext
    {
        public bdTDS_AlmoxarifadoEntities1()
            : base("name=bdTDS_AlmoxarifadoEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Area> Area { get; set; }
        public DbSet<Colaborador> Colaborador { get; set; }
        public DbSet<Entrada> Entrada { get; set; }
        public DbSet<ItensEntrada> ItensEntrada { get; set; }
        public DbSet<ItensSaida> ItensSaida { get; set; }
        public DbSet<Produto> Produto { get; set; }
        public DbSet<Saida> Saida { get; set; }
    }
}
