//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDSAlmoxarifado.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produto
    {
        public Produto()
        {
            this.ItensEntrada = new HashSet<ItensEntrada>();
            this.ItensEntrada1 = new HashSet<ItensEntrada>();
            this.ItensEntrada2 = new HashSet<ItensEntrada>();
            this.ItensSaida = new HashSet<ItensSaida>();
            this.ItensSaida1 = new HashSet<ItensSaida>();
            this.ItensSaida2 = new HashSet<ItensSaida>();
        }
    
        public int PROID { get; set; }
        public string PRODESCRICAO { get; set; }
        public Nullable<int> PROMINIMO { get; set; }
        public Nullable<int> PROMAXIMO { get; set; }
        public Nullable<int> PROESTOQUE { get; set; }
    
        public virtual ICollection<ItensEntrada> ItensEntrada { get; set; }
        public virtual ICollection<ItensEntrada> ItensEntrada1 { get; set; }
        public virtual ICollection<ItensEntrada> ItensEntrada2 { get; set; }
        public virtual ICollection<ItensSaida> ItensSaida { get; set; }
        public virtual ICollection<ItensSaida> ItensSaida1 { get; set; }
        public virtual ICollection<ItensSaida> ItensSaida2 { get; set; }
    }
}
