//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDSAlmoxarifado.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Saida
    {
        public Saida()
        {
            this.ItensSaida = new HashSet<ItensSaida>();
            this.ItensSaida1 = new HashSet<ItensSaida>();
            this.ItensSaida2 = new HashSet<ItensSaida>();
        }
    
        public int SAIDAID { get; set; }
        public System.DateTime SAIDADATA { get; set; }
        public string SAIDAOBSERVACAO { get; set; }
        public int COLID { get; set; }
    
        public virtual Colaborador Colaborador { get; set; }
        public virtual Colaborador Colaborador1 { get; set; }
        public virtual Colaborador Colaborador2 { get; set; }
        public virtual ICollection<ItensSaida> ItensSaida { get; set; }
        public virtual ICollection<ItensSaida> ItensSaida1 { get; set; }
        public virtual ICollection<ItensSaida> ItensSaida2 { get; set; }
    }
}
