//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniCurso.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produto
    {
        public int CODIGOPRODUTO { get; set; }
        public string DESCRICAOPRODUTO { get; set; }
        public float PRECOPRODUTO { get; set; }
    }
}
