use TDSAlmoxarifado
go
create table AREA(
 AREID INT IDENTITY(1,1) PRIMARY KEY,
 AREADESCRICAO VARCHAR(100) NOT NULL
 )
 go
 INSERT AREA VALUES ('TI')
 INSERT AREA (AREADESCRICAO) VALUES ('COZINHA')
 go	
 SELECT * FROM AREA
 select areid, areadescricao from AREA
 select areid as 'Código', areadescricao 'Descrição' from AREA
 --Ordem crescente pelo campo descrição
 select areid as 'Código', areadescricao 'Descrição' from AREA
 order by AREADESCRICAO asc
 --ordem Decrescente pleo campo descrição
 select areid as 'Código', areadescricao 'Descrição' from AREA
 order by AREADESCRICAO desc
 --Agragando dados
 Select count(areid) as 'Total de Registros' from AREA
 --TABLE COLABORADOR
 Create table COLABORADOR(
 COLID INT IDENTITY(1,1) PRIMARY KEY,
 COLNAME VARCHAR(100) NOT NULL,
 COLCARGO VARCHAR(100) NULL,
 AREID INT,
 FOREIGN KEY (AREID) REFERENCES AREA(AREID)
 )
 --INSERINDO NOVOS COLABORADORES
 INSERT COLABORADOR VALUES ('Reginaldo',null, 1)
 INSERT COLABORADOR (COLNAME,AREID) VALUES ('Breno',2)
 --SELECIONAR COLABORADORES
 SELECT * FROM COLABORADOR
--atualizar dados
 UPDATE COLABORADOR
 SET COLCARGO='Tio'

 UPDATE COLABORADOR
 SET COLCARGO='Fazendeiro'
 WHERE COLID=2
 --deletar
 delete COLABORADOR
 where COLID=4
 --tentando apagar uma área que tem colaborador
 select * from AREA
 where AREID=2
 --join
 select C.COLID 'Código',
		C.COLNAME 'Nome',
		C.COLCARGO 'Cargo',
		A.AREADESCRICAO 'Área'
		from COLABORADOR C JOIN
			AREA A ON C.AREID=A.AREID
--mais testes
INSERT COLABORADOR (COLNAME,AREID) VALUES ('Ryandra',1)
INSERT COLABORADOR (COLNAME,AREID) VALUES ('Marcus',1)
--
select AREID 'Código Área', 
	COUNT(AREID) 'Quantidade' FROM COLABORADOR
GROUP BY AREID, COLNAME
--Table Produto
CREATE TABLE PRODUTO (
	PROID INT identity(1,1) PRIMARY KEY,
	PRODESCRICAO VARCHAR(100) NOT NULL,
	PROMINIMO INT DEFAULT 0 CHECK (PROMINIMO>=0),
	PROMAXIMO INT DEFAULT 0 CHECK (PROMAXIMO>=0),
	PROESTOQUE INT DEFAULT 0 CHECK (PROESTOQUE>=0)
)
go
--drop table produto
select * from PRODUTO
insert PRODUTO (PRODESCRICAO)
 values ('Feijão')
insert PRODUTO
 values ('Banana',0,100,10)
insert PRODUTO (PRODESCRICAO, PROMINIMO, PROMAXIMO, PROESTOQUE)
 values ('Ratinho', 1,20,40)
 --tabela entrada
 Create table ENTRADA(
  ENTID INT PRIMARY KEY IDENTITY(1,1),
  ENTDATA DATETIME NOT NULL,
  ENTORIGEM VARCHAR(100) DEFAULT 'PADRÃO' NULL,
  ENTNUMERONOTA VARCHAR(100) NULL,
  ENTOBSERVACAO VARCHAR(1000)
 )
GO
 SELECT * FROM ENTRADA
GO
 INSERT ENTRADA (ENTDATA, ENTORIGEM, ENTNUMERONOTA, ENTOBSERVACAO)
	VALUES('2022-27-07','Padrão','002555','A NOTA É MINHA')
GO
 INSERT ENTRADA (ENTDATA, ENTORIGEM, ENTNUMERONOTA, ENTOBSERVACAO)
	VALUES('2022-27-07','Padrão','001454','Menos 1 para Jhonas.')
GO
INSERT ENTRADA (ENTDATA, ENTORIGEM, ENTNUMERONOTA, ENTOBSERVACAO)
	VALUES('2022-27-06','Padrão','002555','A NOTA É MINHA')
GO
 INSERT ENTRADA (ENTDATA, ENTORIGEM, ENTNUMERONOTA, ENTOBSERVACAO)
	VALUES('2022-30-01','Padrão','0024444','Anote ai Ryandra')
GO
--NOTAS DEPOIS DE JANEIRO DE 2022
SELECT * FROM ENTRADA WHERE ENTDATA > '2022-31-01 00:00:00.000'
--NOTAS NO MÊS DE JUNHO
SELECT * FROM ENTRADA WHERE ENTDATA <= '2022-01-06' AND ENTDATA <= '2022-30-06'
---
SELECT * FROM ENTRADA WHERE MONTH(ENTDATA)=6 AND YEAR(ENTDATA)='2022'
---
SELECT * FROM ENTRADA WHERE YEAR(ENTDATA)='2022'
---SELECIONAR AS NOTAS EM QUE A OBSERVAÇÃO CONTENHA RYANDRA
SELECT * FROM ENTRADA WHERE YEAR(ENTDATA)='2022' AND ENTOBSERVACAO LIKE '%Ryandra%'
---SELECIONAR TODAS AS NOTAS QUE A ORIGEM SEJA A LETRA P
SELECT * FROM ENTRADA WHERE ENTORIGEM LIKE 'p%'

---TABLE ITENS ENTRADA
CREATE TABLE ITENSENTRADA(
	ITEID INT PRIMARY KEY IDENTITY(1,1),
	ITEQUANTIDADE INT NOT NULL CHECK(ITEQUANTIDADE>0),
	ITEPRECO NUMERIC(18,2) CHECK (ITEPRECO>0) NOT NULL,
	ITETOTAL AS ITEQUANTIDADE*ITEPRECO,
	ENTID INT NOT NULL,
	PROID INT NOT NULL,
	FOREIGN KEY (ENTID) REFERENCES ENTRADA(ENTID),
	FOREIGN KEY (PROID) REFERENCES PRODUTO(PROID)
)
---
Insert ITENSENTRADA (ENTID,PROID, ITEQUANTIDADE,ITEPRECO) values(2,1,10,9.50)
Insert ITENSENTRADA (ENTID,PROID, ITEQUANTIDADE,ITEPRECO) values(2,2,5,2.78)
---
select I.ITEID 'Número Item',
	   E.ENTDATA 'Data',
	   P.PRODESCRICAO 'Produto',
	   I.ITEQUANTIDADE 'Quantidade',
	   I.ITEPRECO 'Valor',
	   I.ITETOTAL ' Total'
	   FROM ITENSENTRADA I
	   JOIN ENTRADA E ON I.ENTID=E.ENTID
	   JOIN PRODUTO P ON I.PROID=P.PROID
---
